import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AnalyticsProvider } from "@/providers/analytics-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* As stated in the README, you can initialize Ours Analytics in two ways:
          
          1. Using the NPM package (recommended):
             - Import 'ours-web-sdk'
             - Use the <AnalyticsProvider /> component (already implemented below)
          
          2. Using the script tag (alternative):
             - Uncomment and paste your snippet from the Ours dashboard below
        */}

        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
              // Paste your Ours Privacy Analytics initialization snippet here
            `
          }}
        /> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <AnalyticsProvider />
      </body>
    </html>
  );
}
